version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tg_bid
    ports:
      - "8881:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      GUNICORN_ACCESS_LOGFILE: "/dev/null"
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  admin-server:
    build:
      context: ./admin-server
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    restart: unless-stopped

  admin-client:
    build:
      context: ./admin-client
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - admin-server
    ports:
      - "3000:80"
    restart: unless-stopped

  spec-bot:
    build:
      context: ./spec-bot
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    restart: unless-stopped

  request-bot:
    build:
      context: ./request-bot
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
  pgadmin_data:
