version: "3.9"

services:
  db:
    image: postgres:16
    container_name: tg_bid-postgres
    environment:
      POSTGRES_DB: tg_bid
      POSTGRES_USER: tg_bid_user
      POSTGRES_PASSWORD: tg_bid_password
      TZ: ${TZ:-Europe/Prague}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: tg_bid-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db


  bot:
    build: ./bot
    env_file: ./bot/.env
    environment:
      TZ: ${TZ:-Europe/Prague}
    depends_on:
      - db
    restart: unless-stopped

  dm_bot:
    build: ./dm_bot
    env_file: ./dm_bot/.env
    environment:
      TZ: ${TZ:-Europe/Prague}
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pg_data:
