[project]
name = "tg-requests-admin"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "aiogram==3.13.1",
  "pydantic-settings==2.6.1",
  "asyncpg==0.30.0",
  "openpyxl==3.1.5",
]

[tool.pdm]
