[project]
name = "tg-requests-publisher"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "aiogram==3.13.1",
  "pydantic-settings==2.6.1",
  "asyncpg==0.30.0",
  "PyJWT==2.9.0",
]

[tool.pdm]
